### ISSUE TITLE
[Feature 🔮]: Random Song Generator 

### ISSUE THREAD

**Issue by Daniel1785** [InsideAgent/InsideAgentBot#6]
### Feature Request requirements.

- [X] I have searched the [issues](https://github.com/InsideAgent/InsideAgentBot/issues) page for duplicates.
- [X] I have checked the [Pull Request](https://github.com/InsideAgent/InsideAgentBot/pulls) page for this feature.
- [ ] I am willing to PR this feature myself.
- [X] I have external information to clarify the request (photo/video/files/links).

### Description

Hello! I have a random song generator (perchance.org/generatethatsong) that i want to make into a bot that generates random songs and plays them in VC

### Please attach any other files/screenshots/videos/information below!

Commands would be:
/gen 2020pop(generates a song from the 2020s pop cat.)
/gen 2010pop(generates a song from the 2010s pop cat.)
/gen 2000pop(generates a song from the 2000s pop cat.)
/gen 2020alt(generates a song from the 2020s alt cat.)
/gen 2010alt(generates a song from the 2010s alt cat.)
/gen 2000alt(generates a song from the 2000s alt cat.)
/gen random for a song from any category.
For VC, just add VC to the prefix, /vc gen ....

**Comment by Jacrispys** [comment]
I plan on adding the genres into a preset list along with a third argument for amount of songs to generate, would look something like this:

`/radio pop-2000 50`

will find an API for song generation or template this: https://perchance.org/generatethatsong
